[package]
name = "cachedb"
version = "0.0.0"
authors = ["Christian Thäter <ct@pipapo.org>"]
edition = "2018"
description = "Key/Value store that stores Arc<RwLock<>> which expire in LRU order when unused"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cehteh/cachedb.git"
keywords = ["collection", "cache"]

[dependencies]
parking_lot = "0.11"
log = "0.4"

[dev-dependencies]
rand = "0.8.4"
simple_logger = "1.13.0"

[badges]
maintenance = { status = "actively-developed" }
